{
	if (side _x == west) then 
	{
		_x createDiaryRecord ["Diary", ["Markers", "Charlie Markers (C-#): HVT Convoy Positions<br/>Papa Markers (P-#): OPFOR Patrols<br/>Romeo Markers (R-#): Rendezvous Intel"]];
		
		_x createDiaryRecord ["Diary", ["Execution", "The convoy will be moving at around 19:00, just before night fall. It is highly recommended that your team bring proper night equipment, just in case.<br/><br/>If you plan to ambush the convoy, be prepared to bring plenty of anti-vehicle equipment, including mines.<br/><br/>If you plan to assault Charlie-4 during the meeting, it's advised that you bring silencers, med-long range rifles, and proper optics. Taking out any patrols quietly and from a distance will help avoid getting swarmed by OPFOR."]];
		
		_x createDiaryRecord ["Diary", ["Mission", "Eliminate the HVT and his contact by any means necessary.<br/><br/>Command has reccomended two strategies to execute the mission but the fluid nature of the mission gives your team some freedom of choice in the matter:<br/><br/>1. Intercept and ambush the HVT convoy en route to <marker name='convoy_end'>Charlie-4</marker> then eliminate the contact seperately. The rendezvous point is likely to be heavily guarded so an ambush away from the bulk of the OPFOR could give you a big advantage. However, you'll need to move fast to set up any explosive or killzones on the convoy's path.<br/><br/>2. Move to <marker name='convoy_end'>Charlie-4</marker> and wait for the meeting to happen. With both targets in the same location, eliminating them both before they have the chance to escape would be much easier. However, the meeting location is usually surrounded by several patrols and garrisoned with at least two squads. Resistance may be heavy.<br/><br/>3. Execute your own plan. Command recognizes that this mission is far from predictable and has given your team the tactical freedom to accomplish the mission however you see fit."]];
		
		_x createDiaryRecord ["Diary", ["Situation", "An OPFOR High Value Target is planning to meet a contact at <marker name='convoy_end'>Charlie-4</marker> this evening. The HVT is a high-ranking officer and his contact is a lower officer who is quickly moving up the ranks.<br/><br/>The HVT convoy is scheduled to leave from <marker name='convoy_start'>Charlie-1</marker> at approximately 19:10 and is expected to arrive at <marker name='convoy_end'>Charlie-4</marker> within 10 minutes of their departure. We've observed that these convoys typically pass through <marker name='charlie_2'>Charlie-2</marker> and <marker name='charlie_3'>Charlie-3</marker>. The expected route is marked on the map in red dots.<br/><br/>A four-man recon unit, Recon 1-1 through 1-4, has been stationed along the convoy route and will provide updates when capable. However, due to recent increases in OPFOR patrols, each Recon spotter will peel off and RTB once the convoy has passed beyond their sight.<br/><br/>Recon 1-1 will inform your team when the convoy has embarked."]];
	}
} foreach allUnits;